### PR TITLE
Fix compiling by checking the installed mbstring extension

### PR DESCRIPTION
**Pull request by rhabacker**

### CODE REVIEW

**Comment by rhabacker** [comment]
anyone here who can merge this pull request ?

**Comment by remicollet** [comment]
Sorry, but this is not correctn mbstring can be build statically, so without mbstring.so

**Comment by rhabacker** [comment]
How could it be detected that mbstring is build statically ?

**Comment by remicollet** [comment]
Done in 2228359b786375cdc4b37303f82b8d97542bc8f4

**Comment by remicollet** [comment]
> How could it be detected that mbstring is build statically ?

@m6w6 have a nice PECL_HAVE_EXT macro for this....  (see pecl_http extension)

**Pull request closed without merging**
